#!/bin/bash

EXEC=$(which bash)
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

$EXEC "$DIR/build-zlib" && $EXEC "$DIR/build-openssl" && $EXEC "$DIR/build-nginx-rtmp-module" && $EXEC "$DIR/build-nginx"
