#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source "$DIR/vars"

ACTION=""

if [ -d "$OPENSSL_SOURCES" ]
then
  ACTION="updating OpenSSL sources"

  echo "$ACTION..."

  cd "$OPENSSL_SOURCES" && git pull origin master > /dev/null 2>&1 && make clean
else
  ACTION="obtaining OpenSSL sources"

  echo "$ACTION..."

  git clone "$OPENSSL_GIT" "$OPENSSL_SOURCES" > /dev/null 2>&1
fi

echo "done $ACTION"


cd "$OPENSSL_SOURCES" \
  && ./config \
    --prefix="$OPENSSL_PREFIX" \
    --release \
    --openssldir="$OPENSSL_PREFIX/ssl" \
    no-deprecated \
    no-legacy \
    && make && make install
